# Generated by Django 5.0.6 on 2024-06-26 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortURL', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortURLs',
            new_name='ShortURL',
        ),
    ]
